terminal-labs/rambo

CHANGELOG.md, salt_resources/states/postgresql/init.sls
... and making use of existing artifact_db grain.
=> [hotfix-8-4-17-3] Adding artifact requirement to loading a db

CHANGELOG.md, salt_resources/grains/grains, salt_resources/states/git/ssh.sls, salt_resources/states/hg/ssh.sls
=> [hotfix-8-4-17] state names for known_host, timeout, default fingerprints

Vagrantfile, salt_resources/states/network/init.sls, salt_resources/states/top.sls
Also, this fixes provisioning with a repo branch specified. That previously failed to call the highstate.
=> Setting hostname to VM_NAME

salt_resources/states/network/init.sls, vagrant_resources/modules.rb
=> Shrinking unique identifier, fixing hostname / no sudo bug

.gitignore, CHANGELOG.md, README.md, docs/INSTALL.md, docs/providers/digitalocean.md, vagrant_resources/vagrant/Vagrantfile.digitalocean
and other docs tweaks. ref #70
=> Multiuser support on DO

CHANGELOG.md, Vagrantfile
=> Detect and remove broken symlinks

rambo/cli.py
=> Add -h alias to --help.

README.md, RULES.md, docs/INSTALL.md, docs/providers/aws-ec2.md, rambo/setup.sh
=> Adding documentation for CLI / API, and various small tweaks / docs fixes.

CHANGELOG.md, rambo/salt_resources/states/basebox/init.sls, rambo/salt_resources/states/top.sls, rambo/salt_resources/states/users/init.sls
=> Ensure existence of bashrc file (bugfix)

rambo/Vagrantfile, rambo/vagrant_resources/modules.rb, rambo/vagrant_resources/vagrantfiles/digitalocean, rambo/vagrant_resources/vagrantfiles/ec2, rambo/vagrant_resources/vagrantfiles/lxc, rambo/vagrant_resources/vagrantfiles/virtualbox
1) created ruby functions set/get_env_var_rb() to mimic pythons funcTions set/get_env_var() in utils.py
2) changed load modules.rb to require_relative modules.rb to use functions more than once
3) replaced all ENV[" "] to do with RAMBO_variable with the new ruby get/set functions
4) created the RAMBO_GUEST environment variable to replace VM_HOST
resolves issue #186
=> created ruby env var get/set functions, replaced all code effected

rambo/app.py, rambo/cli.py, setup.py
Shell invocation outputs in near real-time, stdout and stderr are both
logged, and stderr logged again in a separate location, ANSI formatting
is kept, and exit status is captured.
Fixes #150, #140, and #194
=> [rambo-150] Refactored shell invocation and logging. Fixes #150.

rambo/app.py, rambo/cli.py
=> [rambo-210] Changing name of init cmd to setup and tweaked help

setup.py
=> Remove click use in setup.py

rambo/app.py
replaced all '+' concatenation with os.path.join concatenation for file paths
#200
=> Consolidated file path concatenation

docs/cli.md, rambo/app.py, rambo/cli.py
Pull after #291.
Fixes #290, #230 
Includes docs updates.
=> Adding halt and scp

rambo/app.py
Fixes #314 
All API related fixes for bugs introduced mainly in #311:
- Consistently using **params for base `rambo` options throughout app.py.
- Adding missing ability to set base options in `scp`
- Added ability to not have to separately call the `set_init_vars` and `set_vagrant_vars` functions.
- Using `.get` dict method instead of direct item reference by key when we shouldn't rely on the key's existence. I.e. Do `dict.get('key')` instead of `dict['key']` when it's ok for the key to not exist.
With these changes, you can now pass the base options with `params` in any API call. E.g.
```python
from rambo.app import up, ssh
params = {'cwd' : '/home/user', 'guest_os' : 'debian-9'}
up(**params)
ssh(**params)
```
TODO:
- make a ticket for rewriting `if not ctx: # Using API. Else handled by …
=> Consistently use **params. Fixes key refs.

rambo/app.py
We weren't actually changing the cwd! Now we do.
=> [cwd-hotfix] Actually setting the cwd.

rambo/Vagrantfile, rambo/app.py, rambo/cli.py, rambo/options.py
=> added in option flag to set custom sync dir

rambo/Vagrantfile
(issue reference)
Fixes #329
Does this deserve / include a changlog entry?
No -Joe
=> now setting randomtag grain

rambo/Vagrantfile
**(issue reference)**
Fixes #341 
=> removed "--log-level info"

rambo/app.py, rambo/cli.py, rambo/options.py, rambo/vagrant/vagrantfiles/virtualbox
No. Since this will not necessarily survive current refactoring for saltstack based backend.
=> [boxes] Adding in support for alternate Vagrant boxes as cli and conf args.

rambo/vagrant/modules.rb
=> [hotfix-10-16-18] Fixing missing require.

rambo/Vagrantfile
No, minor, and might not survive refactoring.
=> [hotfix-10-16-18-2] Gracefully failing if custom sources don't exist.

rambo/Vagrantfile
=> installing salt

rambo/vagrant/vagrantfiles/digitalocean
=> force the use of rsync
